#!/bin/sh

# Create OIDC config for 000-default.conf to load
cat <<-EOF > /etc/apache2/conf-available/oidc.conf
    # Setup OpenID Connect Authentication
    OIDCProviderMetadataURL ${OIDC_METADATA_URL}
    OIDCClientID ${OIDC_CLIENT_ID}
    OIDCClientSecret ${OIDC_CLIENT_SECRET}
    OIDCRedirectURI ${OIDC_REDIRECT_URI}
    OIDCResponseType code
    # OIDCScope "openid profile email"
    OIDCScope "openid profile email"
    OIDCSSLValidateServer On
    OIDCCryptoPassphrase ${OIDC_CRYPTO_PASSPHRASE}
    OIDCPassClaimsAs environment
    OIDCClaimPrefix USERINFO_
    OIDCPassIDTokenAs payload
EOF

chown www-data:www-data /etc/apache2/conf-available/oidc.conf
chmod 440 /etc/apache2/conf-available/oidc.conf

docker-php-entrypoint "$@"